# This is a config for E2B sandbox template.
# You can use template ID (to5j87tb7az4dyy8zjh9) or template name (lovable-nextjs-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-nextjs-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-nextjs-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-nextjs-template')

team_id = "9ac77b88-b23e-44bc-8587-f33e81688c29"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-nextjs-template"
template_id = "to5j87tb7az4dyy8zjh9"
